### PR TITLE
Add first draft of a chapter on using Webmin as an alternative method ...

### PR DESCRIPTION
**Pull request by rverrips**
… for administration of Laravel Forge Provisioned Servers.

Webmin is a browser driven way of updating configuration files, viewing log files, etc. 

Todo
1 - I'll have a youtube video of this up soon (just editing it)
2 - Want to give some more example of using Webmin (i.e. showing log files, uploading files, killing processors, creating cron jobs, etc.) 
3 - I need to completing the chapter with "hardening section" on 2-factor Auth, SSL, etc.

### CODE REVIEW

**Comment by jackfruh** [comment]
Hey Roy! Thanks so much for contributing this chapter!

When I first saw the pull request and peeked into webmin, my first thought was that I wasn't sure if this was a fit for this book.

Then I looked at the video, and the video is fantastic.
It shows enough forge usage that it's worth people watching, even if they aren't interested in webmin.
Towards the end of the video, around the 14:20 mark you said something that totally rang true, which was that webmin had become a bit of a learning tool for you, and I can totally see that!

So now I'm on the fence.

On one hand, I think this and phpmyadmin are going in the opposite direction from the book's intention, and I have some reservations about having a book suggest that people install external tools like that - with each one, there's a new possibility of vulnerability that doesn't exist in an 'out of the box' forge provisioned server.

On the other hand, webmin looks useful and I see you have plans to add some security related steps so maybe the security concerns already have an answer out there. 

What are your thoughts?

- Jack

**Comment by rverrips** [comment]
Hey Jack

Thanks for the feedback.  Indeed, as I was listening to your comments on Laravel News about your book (things you wished you knew like log file locations, etc.) I was reminded how having Webmin 15 years ago taught me all that stuff (and ‘till today still does) hence the quick “Show and Tell” Video/Chapter Draft as a possible alternative. 

I mainly wrote the chapter draft/video for you, Jack, hoping it could help along your path of finding log files, learn about the daemons/services and their config file options, etc.    

Note though that Webmin out the box is pretty secure, and if anything allows the novice forge server admin a quick way to enhance security for Webmin itself with restricting IP access to a limited set of IPs, two factor Auth, SSL comms’ etc.   Beyond that, Webmin further quickly allows securing of both the base of ubuntu (turn on daily security updates with notifications) and allows for clarity in securing the deamons/services as well, along with admin tools like backup/restore etc.  

What I didn’t really want to do was suggest a second book like "Administering Forge Servers with Webmin” but if the direction is so divergent that may well be an option. 

I’m happy to support either way :)

Yours

Roy

**Comment by jackfruh** [comment]
Thanks Roy!

I appreciate your efforts so much!

 How much work would it be to add in a section on the auth options like two factor, SSL, VPN etc?  Is that something you'd be able/willing to to do?

This thing is really really neat and the more I think about it, the more excited I get!

I'd love to include the basics as a chapter in this book.  

We could always see where it goes from there- if there are lots of questions, maybe a second book makes sense, if not then at least the basics are out there for people to see.


- Jack

**Comment by rverrips** [comment]
>> How much work would it be to add in a section on the auth options like two factor, SSL, VPN etc?

Not much effort, just need to find the time ... I'll try get this done in the next few days and submit a PR

**Pull request merged**
